/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "var(--md-primary)",
        "on-primary": "var(--md-on-primary)",
        "primary-container": "var(--md-primary-container)",
        "on-primary-container": "var(--md-on-primary-container)",
        "primary-fixed": "var(--md-primary-fixed)",
        "primary-fixed-dim": "var(--md-primary-fixed-dim)",
        "on-primary-fixed": "var(--md-on-primary-fixed)",
        "on-primary-fixed-variant": "var(--md-on-primary-fixed-variant)",
        "secondary": "var(--md-secondary)",
        "on-secondary": "var(--md-on-secondary)",
        "secondary-container": "var(--md-secondary-container)",
        "on-secondary-container": "var(--md-on-secondary-container)",
        "secondary-fixed": "var(--md-secondary-fixed)",
        "secondary-fixed-dim": "var(--md-secondary-fixed-dim)",
        "on-secondary-fixed": "var(--md-on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--md-on-secondary-fixed-variant)",
        "tertiary": "var(--md-tertiary)",
        "on-tertiary": "var(--md-on-tertiary)",
        "tertiary-container": "var(--md-tertiary-container)",
        "on-tertiary-container": "var(--md-on-tertiary-container)",
        "tertiary-fixed": "var(--md-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--md-tertiary-fixed-dim)",
        "on-tertiary-fixed": "var(--md-on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--md-on-tertiary-fixed-variant)",
        "error": "var(--md-error)",
        "on-error": "var(--md-on-error)",
        "error-container": "var(--md-error-container)",
        "on-error-container": "var(--md-on-error-container)",
        "surface": "var(--md-surface)",
        "on-surface": "var(--md-on-surface)",
        "surface-variant": "var(--md-surface-variant)",
        "on-surface-variant": "var(--md-on-surface-variant)",
        "surface-container-lowest": "var(--md-surface-container-lowest)",
        "surface-container-low": "var(--md-surface-container-low)",
        "surface-container": "var(--md-surface-container)",
        "surface-container-high": "var(--md-surface-container-high)",
        "surface-container-highest": "var(--md-surface-container-highest)",
        "surface-bright": "var(--md-surface-bright)",
        "surface-dim": "var(--md-surface-dim)",
        "surface-tint": "var(--md-surface-tint)",
        "outline": "var(--md-outline)",
        "outline-variant": "var(--md-outline-variant)",
        "inverse-surface": "var(--md-inverse-surface)",
        "inverse-on-surface": "var(--md-inverse-on-surface)",
        "inverse-primary": "var(--md-inverse-primary)",
        "background": "var(--md-background)",
        "on-background": "var(--md-on-background)",
        "separator": "var(--md-separator)",
        "accent": "var(--color-accent)",
        "accent-hover": "var(--color-accent-hover)",
        "accent-subtle": "var(--color-accent-subtle)",
        "accent-border": "var(--color-accent-border)",
        "accent-text": "var(--color-accent-text)",
        "reward": "var(--color-reward)",
        "reward-hover": "var(--color-reward-hover)",
        "reward-subtle": "var(--color-reward-subtle)",
        "reward-border": "var(--color-reward-border)",
        "reward-text": "var(--color-reward-text)",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.75rem",
        full: "9999px"
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px",
        gutter: "24px",
        "container-max": "1200px"
      },
      fontFamily: {
        sans: ["General Sans", "Inter", "system-ui", "-apple-system", "sans-serif"],
        clash: ["Clash Display", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["34px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "title-lg": ["22px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "1.5", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "caption": ["11px", { lineHeight: "1.3", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      animation: {
        "fade-in": "fadeIn 0.4s ease-out",
        "slide-up": "slideUp 0.4s ease-out",
        "slide-in-left": "slideInLeft 0.3s ease-out",
        "scale-in": "scaleIn 0.3s ease-out",
        "pulse-soft": "pulseSoft 2s ease-in-out infinite",
        "counter": "counter 1.5s ease-out forwards",
        "progress": "progress 1s ease-out forwards",
      },
      keyframes: {
        fadeIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp: { "0%": { opacity: "0", transform: "translateY(20px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        slideInLeft: { "0%": { opacity: "0", transform: "translateX(-20px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        scaleIn: { "0%": { opacity: "0", transform: "scale(0.95)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        pulseSoft: { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.7" } },
        progress: { "0%": { width: "0%" }, "100%": { width: "var(--progress)" } },
      }
    }
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
